#![no_std]

use soroban_sdk::{
    contract, contracterror, contractevent, contractimpl, contracttype, Address, BytesN, Env, Vec,
};

// Clients generated from the compiled zk_verifier / ofac_verifier contracts.
// Build both first: `stellar contract build --package zk_verifier --package ofac_verifier`
mod firma_verifier {
    soroban_sdk::contractimport!(
        file = "../../target/wasm32v1-none/release/zk_verifier.wasm"
    );
}

mod ofac_verifier {
    soroban_sdk::contractimport!(
        file = "../../target/wasm32v1-none/release/ofac_verifier.wasm"
    );
}

/// pubkeyHash, nullifier, ageAbove18, nullifierSeed, signalHash.
const FIRMA_NULLIFIER_INDEX: u32 = 1;
const FIRMA_SIGNAL_HASH_INDEX: u32 = 4;

/// [ofacRoot, addressHash]
const OFAC_ROOT_INDEX: u32 = 0;
const OFAC_ADDRESS_HASH_INDEX: u32 = 1;

#[contracttype]
#[derive(Clone)]
pub struct Proof {
    pub a: BytesN<64>,
    pub b: BytesN<128>,
    pub c: BytesN<64>,
    pub pub_signals: Vec<BytesN<32>>,
}

#[contractevent]
pub struct IdentityVerified {
    #[topic]
    pub wallet: Address,
}

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    NotAdmin = 3,
    WrongFirmaSignalsLen = 4,
    WrongOfacSignalsLen = 5,
    SignalHashMismatch = 6,
    StaleOfacRoot = 7,
    InvalidFirmaProof = 8,
    InvalidOfacProof = 9,
    FirmaIdentityClaimedByOtherWallet = 10,
}

#[contracttype]
enum DataKey {
    Admin,
    FirmaVerifierId,
    OfacVerifierId,
    /// The OFAC sanctions-list SMT root this contract currently accepts.
    /// Sanctions lists change over time, so this is admin-updatable after
    /// `initialize`, independently of the verifier contract addresses.
    OfacRoot,
    Verified(Address),
    /// Maps a Firma Digital nullifier to the one wallet allowed to use it.
    /// Keeps the same real-world identity from being bound to more than one
    /// Stellar address, while still letting that same wallet re-verify
    /// (e.g. to refresh an OFAC check against an updated sanctions list).
    FirmaNullifierOwner(BytesN<32>),
}

#[contract]
pub struct IdentityGate;

#[contractimpl]
impl IdentityGate {
    /// One-time initialization. Caller becomes admin.
    pub fn initialize(
        env: Env,
        admin: Address,
        firma_verifier_id: Address,
        ofac_verifier_id: Address,
        ofac_root: BytesN<32>,
    ) -> Result<(), Error> {
        if env.storage().instance().has(&DataKey::Admin) {
            return Err(Error::AlreadyInitialized);
        }

        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage()
            .instance()
            .set(&DataKey::FirmaVerifierId, &firma_verifier_id);
        env.storage()
            .instance()
            .set(&DataKey::OfacVerifierId, &ofac_verifier_id);
        env.storage().instance().set(&DataKey::OfacRoot, &ofac_root);

        Ok(())
    }

    /// Admin-only: update the accepted OFAC sanctions-list root as the
    /// off-chain SMT is refreshed against new sanctions data.
    pub fn set_ofac_root(env: Env, admin: Address, new_root: BytesN<32>) -> Result<(), Error> {
        admin.require_auth();

        let stored_admin: Address = env
            .storage()
            .instance()
            .get(&DataKey::Admin)
            .ok_or(Error::NotInitialized)?;
        if admin != stored_admin {
            return Err(Error::NotAdmin);
        }

        env.storage().instance().set(&DataKey::OfacRoot, &new_root);
        Ok(())
    }

    /// Verify that `wallet` holds a valid ZK Firma Digital credential AND
    /// passes the OFAC non-sanctions check, with both proofs bound to the
    /// same underlying address.
    ///
    /// ## How the binding actually works
    ///
    /// The OFAC circuit (`NotInOFACBlacklist`) constrains
    /// `addressHash = Poseidon(addressLo, addressHi)` for a private address
    /// split into two 128-bit limbs, and proves that hash is absent from the
    /// sanctions-list SMT identified by `ofacRoot`.
    ///
    /// The Firma Digital circuit's `signalHash` is *not* similarly
    /// constrained inside that circuit -- it is a free public input the
    /// prover commits to ("any message to commit to", per the circuit's own
    /// doc comment), with only a dummy non-tampering constraint. Soroban
    /// (like the original Solidity contracts) leans on the off-chain prover
    /// convention that `signalHash` is set to the *same*
    /// `Poseidon(addressLo, addressHi)` value used in the OFAC proof.
    ///
    /// So this contract checks `firma_proof.signalHash == ofac_proof.addressHash`,
    /// which proves both proofs were generated by someone who knows the
    /// preimage of that one address hash, and that address is OFAC-clear.
    /// It does **not** independently prove that hash corresponds to
    /// `wallet`'s actual Stellar key bytes: Soroban's `Address` type does not
    /// expose raw public-key bytes to contract code, and there is no
    /// Poseidon host function to recompute the hash on-chain even if it did.
    /// That link -- "the off-chain prover used *my* wallet's bytes as
    /// addressLo/addressHi" -- is enforced by `wallet.require_auth()` (only
    /// the real key holder can submit this call) combined with off-chain
    /// discipline in however these proofs get generated, not by an
    /// independent on-chain recomputation.
    pub fn verify_identity(
        env: Env,
        wallet: Address,
        firma_proof: Proof,
        ofac_proof: Proof,
    ) -> Result<(), Error> {
        wallet.require_auth();

        if firma_proof.pub_signals.len() != 5 {
            return Err(Error::WrongFirmaSignalsLen);
        }
        if ofac_proof.pub_signals.len() != 2 {
            return Err(Error::WrongOfacSignalsLen);
        }

        let stored_ofac_root: BytesN<32> = env
            .storage()
            .instance()
            .get(&DataKey::OfacRoot)
            .ok_or(Error::NotInitialized)?;
        if ofac_proof.pub_signals.get_unchecked(OFAC_ROOT_INDEX) != stored_ofac_root {
            return Err(Error::StaleOfacRoot);
        }

        let signal_hash = firma_proof.pub_signals.get_unchecked(FIRMA_SIGNAL_HASH_INDEX);
        if ofac_proof.pub_signals.get_unchecked(OFAC_ADDRESS_HASH_INDEX) != signal_hash {
            return Err(Error::SignalHashMismatch);
        }

        let firma_nullifier = firma_proof.pub_signals.get_unchecked(FIRMA_NULLIFIER_INDEX);
        if let Some(existing_owner) = env
            .storage()
            .persistent()
            .get::<_, Address>(&DataKey::FirmaNullifierOwner(firma_nullifier.clone()))
        {
            if existing_owner != wallet {
                return Err(Error::FirmaIdentityClaimedByOtherWallet);
            }
        }

        let firma_verifier_id: Address = env
            .storage()
            .instance()
            .get(&DataKey::FirmaVerifierId)
            .ok_or(Error::NotInitialized)?;
        let ofac_verifier_id: Address = env
            .storage()
            .instance()
            .get(&DataKey::OfacVerifierId)
            .ok_or(Error::NotInitialized)?;

        let firma_ok = firma_verifier::Client::new(&env, &firma_verifier_id).verify_proof(
            &firma_proof.a,
            &firma_proof.b,
            &firma_proof.c,
            &firma_proof.pub_signals,
        );
        if !firma_ok {
            return Err(Error::InvalidFirmaProof);
        }

        let ofac_ok = ofac_verifier::Client::new(&env, &ofac_verifier_id).verify_proof(
            &ofac_proof.a,
            &ofac_proof.b,
            &ofac_proof.c,
            &ofac_proof.pub_signals,
        );
        if !ofac_ok {
            return Err(Error::InvalidOfacProof);
        }

        env.storage()
            .persistent()
            .set(&DataKey::FirmaNullifierOwner(firma_nullifier), &wallet);
        env.storage()
            .persistent()
            .set(&DataKey::Verified(wallet.clone()), &true);

        IdentityVerified { wallet }.publish(&env);

        Ok(())
    }

    pub fn is_verified(env: Env, wallet: Address) -> bool {
        env.storage()
            .persistent()
            .get(&DataKey::Verified(wallet))
            .unwrap_or(false)
    }
}
